apiVersion: v1
kind: Service
metadata:
  name: kutt
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kutt
  ports:
    - port: {{ .Values.kutt.port }}
      targetPort: {{ .Values.kutt.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kutt
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.kutt.replicaCount }}
  selector:
    matchLabels:
      app: kutt
  template:
    metadata:
      labels:
        app: kutt
    spec:
      containers:
        - name: kutt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.kutt.port }}
          envFrom:
            - configMapRef:
                name: kutt-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_USER
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: JWT_SECRET
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: POSTGRES_DB
          resources:
            {{- toYaml .Values.kutt.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.kutt.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.kutt.port }}
            initialDelaySeconds: 30
            periodSeconds: 20