kutt:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 300Mi

ingress:
  host: 54.198.204.128.nip.io

config:
  defaultDomain: 54.198.204.128.nip.io
  host: 54.198.204.128.nip.io

config:
  defaultDomain: 54.198.204.128.nip.io
  disallowRegistration: "true"